version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(dependabot): "
    open-pull-requests-limit: 5
    labels:
      - "chore"
    target-branch: "main"
