services:
  mysql:
    platform: linux/arm64
    image: mysql:8.4
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: local
      TZ: Asia/Seoul
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d/
    networks:
      - ${NETWORK}
