services:
  mysql:
    image: mysql:latest
    container_name: mysql
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: local
      TZ: Asia/Seoul
    volumes:
      - ./etc/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - ${NETWORK}
